add Dockerfile
wtsnjp/MioGatto pull request #78
Opened 2023-11-22 07:29 UTC by musashi1729

To containerize with Docker, place the Dockerfile in the same hierarchy as MioGatto and grounding-dataset.

Procedure:
Do this in the Dockerfile hierarchy.
`$docker build -t miogatto ./`

Starting a container (first time)
`$docker --name miogatto run -it miogatto`

After the second time
`$docker start -i miogatto`

2023-12-19 01:17 UTC, musashi1729 commented
Dockerfileで、Dockerfileより上位の階層にあるディレクトリをコピーするのが無理なので、runのvオプションでdatasetとsourceのディレクトリにアクセスするようにした。
かなり長い実行コマンドになってしまった...

以下の通り実行してサーバを起動し http://localhost:4100/ にアクセスする。
`$ docker build ./ -t miogatto`
`$ docker run -it --rm -p 4100:4100 -v /path/to/datasets:/MioGatto/data -v /path/to/sources:/MioGatto/sources
 miogatto 1808.02342`

2023-12-19 11:39 UTC, delta-river requested changes

2023-12-19 11:39 UTC, delta-river commented on Dockerfile
> +RUN chmod a+x startup.sh
下の ENTRYPOINT のところのコマンドは bash を使えばここの chmod は無くて良さそうな気がします．
というより，そもそも startup.sh に書いてあるコマンド（python -m server....）をこのエントリーポイントに直接書けば良さそうな気がするのですがどうでしょう？

2023-12-19 11:39 UTC, delta-river commented on Dockerfile
> +RUN apt-get install -y python3-pip
RUN コマンドをすると「レイヤ」を新たに作ることになりイメージを必要以上に大きくしてしまうらしいので，こういったコマンドは && などでつなげるのが定石のようです．

2023-12-19 11:39 UTC, delta-river commented on startup.sh
> +python -m server -d datasets/ -s sources/ --host 0.0.0.0 $@
datasets ではなく，data ですかね．

2023-12-19 11:42 UTC, delta-river commented
お疲れ様です，軽くコメントを入れました．
ディレクトリ名のミスを修正すればぼくの手元でもちゃんと動きました．
grounding-dataset とかのディレクトリを渡すのは -v のオプションでやるのが確かに良い感じですね．

2024-01-12 17:47 UTC, musashi1729 commented on Dockerfile
> +RUN chmod a+x startup.sh
仰る通りchmodの一文は無くせますね。ありがとうございます🙇
シェルスクリプトを介してるのはエントリーポイントに直接書く方法だとコマンドライン引数の渡し方がわからないのと、これから実行文を長くするとき楽かなと思ったからです。

2024-01-16 02:27 UTC, delta-river approved these changes

2024-01-16 02:39 UTC, delta-river commented on Dockerfile
> +RUN chmod a+x startup.sh
entrypoint の引数に関しては，特に何もせずとも docker run の引数がくっつけられるようです．（参考：[https://www.grandream.jp/blog/docker-cmd-entrypoint/](https://www.grandream.jp/blog/docker-cmd-entrypoint/)）

2024-01-16 02:53 UTC, delta-river commented on Dockerfile
> +ENTRYPOINT ["bash","./startup.sh"]
```suggestion
ENTRYPOINT ["python","-m", "server", "--host", "0.0.0.0"]
```

こんな感じで，直接書くだけで引数とかに関する挙動はそのままでいけそうです．
実行文を長くする必要があってこの方法だと困りそうなときにまた改めて startup.sh を導入すれば良いような気がします．

2024-01-16 02:54 UTC, delta-river commented
改めて確認して問題なさそうだったので approve しましたが，startup.sh はやっぱりなくてもいける気がしたので suggestion を追加しておきました．

2024-01-23 04:35 UTC, merged